// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Squareline

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_FirstScreen
void ui_FirstScreen_screen_init(void);
lv_obj_t * ui_FirstScreen;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label3;
void ui_event_btnHome(lv_event_t * e);
lv_obj_t * ui_btnHome;
lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabView2;
void ui_event_KitchenRoom(lv_event_t * e);
lv_obj_t * ui_KitchenRoom;
lv_obj_t * ui_roomName3;
lv_obj_t * ui_LightKitRoom;
lv_obj_t * ui_FanKitRoom;
lv_obj_t * ui_AirKitRoom;
lv_obj_t * ui_titleComp2;
lv_obj_t * ui_CountFanK;
lv_obj_t * ui_CountACK;
lv_obj_t * ui_CountLightK;
lv_obj_t * ui_KitActiveLight;
lv_obj_t * ui_KitActiveFan;
lv_obj_t * ui_KitActiveAC;
void ui_event_BedRoom(lv_event_t * e);
lv_obj_t * ui_BedRoom;
lv_obj_t * ui_roomName4;
lv_obj_t * ui_LightBedRoom;
lv_obj_t * ui_FanBedRoom;
lv_obj_t * ui_AirBedRoom;
lv_obj_t * ui_titleComp1;
lv_obj_t * ui_BedActiveLight;
lv_obj_t * ui_BedActiveFan;
lv_obj_t * ui_BedActiveAC;
lv_obj_t * ui_CountLightB;
lv_obj_t * ui_CountFanB;
lv_obj_t * ui_CountACB;
void ui_event_LvRoom(lv_event_t * e);
lv_obj_t * ui_LvRoom;
lv_obj_t * ui_roomName1;
lv_obj_t * ui_LightLvRoom;
lv_obj_t * ui_FanLvRoom;
lv_obj_t * ui_AirLvRoom;
lv_obj_t * ui_titleComp;
void ui_event_LivActiveLight(lv_event_t * e);
lv_obj_t * ui_LivActiveLight;
lv_obj_t * ui_CountLightLV;
void ui_event_LivActiveFan(lv_event_t * e);
lv_obj_t * ui_LivActiveFan;
lv_obj_t * ui_CountFanLV;
lv_obj_t * ui_LivActiveAC;
lv_obj_t * ui_CountACLV;
void ui_event_TempChart(lv_event_t * e);
lv_obj_t * ui_TempChart;
lv_obj_t * ui_TitleTemp;
lv_obj_t * ui_ValueTemp;
void ui_event_HumidityChart(lv_event_t * e);
lv_obj_t * ui_HumidityChart;
lv_obj_t * ui_TitleHumi;
lv_obj_t * ui_ValueHumi;
lv_obj_t * ui_HeaedMain;
lv_obj_t * ui_TitleVIEW;
lv_obj_t * ui_WifiState;
lv_obj_t * ui_TBState;
// CUSTOM VARIABLES

// SCREEN: ui_LVRoomScreen
void ui_LVRoomScreen_screen_init(void);
lv_obj_t * ui_LVRoomScreen;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_dvName1;
lv_obj_t * ui_lightName1;
void ui_event_LightLvRoom1(lv_event_t * e);
lv_obj_t * ui_LightLvRoom1;
void ui_event_LightLvRoom2(lv_event_t * e);
lv_obj_t * ui_LightLvRoom2;
void ui_event_LightLvRoom3(lv_event_t * e);
lv_obj_t * ui_LightLvRoom3;
void ui_event_BackHome(lv_event_t * e);
lv_obj_t * ui_BackHome;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_dvName2;
lv_obj_t * ui_fanName1;
void ui_event_FanLvRoom1(lv_event_t * e);
lv_obj_t * ui_FanLvRoom1;
void ui_event_FanLvRoom2(lv_event_t * e);
lv_obj_t * ui_FanLvRoom2;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_ACName1;
lv_obj_t * ui_ACLiv1;
void ui_event_ACLvRoom1(lv_event_t * e);
lv_obj_t * ui_ACLvRoom1;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_ACName2;
lv_obj_t * ui_ACLiv2;
void ui_event_ACLvRoom2(lv_event_t * e);
lv_obj_t * ui_ACLvRoom2;
// CUSTOM VARIABLES

// SCREEN: ui_BedoomSceen
void ui_BedoomSceen_screen_init(void);
lv_obj_t * ui_BedoomSceen;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_dvName3;
lv_obj_t * ui_lightName2;
lv_obj_t * ui_LightBedRoom1;
lv_obj_t * ui_LightBedRoom2;
lv_obj_t * ui_LightBedRoom3;
void ui_event_BackHome2(lv_event_t * e);
lv_obj_t * ui_BackHome2;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_dvName4;
lv_obj_t * ui_fanName2;
lv_obj_t * ui_FanBedRoom1;
lv_obj_t * ui_FanBedRoom2;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_ACName3;
lv_obj_t * ui_ACBedRoomTemp1;
lv_obj_t * ui_ACBedRoom1;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_ACName4;
lv_obj_t * ui_ACBedRoomTemp2;
lv_obj_t * ui_ACBedRoom2;
// CUSTOM VARIABLES

// SCREEN: ui_KitchenSceen
void ui_KitchenSceen_screen_init(void);
lv_obj_t * ui_KitchenSceen;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_dvName5;
lv_obj_t * ui_lightName3;
lv_obj_t * ui_SWLightBed1;
lv_obj_t * ui_SWLightBed2;
lv_obj_t * ui_SWLightBed3;
void ui_event_BackHome3(lv_event_t * e);
lv_obj_t * ui_BackHome3;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_dvName6;
lv_obj_t * ui_fanName3;
lv_obj_t * ui_SWFanBed1;
lv_obj_t * ui_SWFanBed2;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_AirKIT1;
lv_obj_t * ui_valTempKIT;
lv_obj_t * ui_SWAirKIT1;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_ACName6;
lv_obj_t * ui_valTempKIT2;
lv_obj_t * ui_SWAirKIT2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_KitchenRoom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_KitchenSceen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_KitchenSceen_screen_init);
    }
}

void ui_event_BedRoom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BedoomSceen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_BedoomSceen_screen_init);
    }
}

void ui_event_LvRoom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LVRoomScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_LVRoomScreen_screen_init);
    }
}

void ui_event_LivActiveLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_CountLightLV, target, "(", ")");
    }
}

void ui_event_LivActiveFan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_CountFanLV, target, "(", ")");
    }
}

void ui_event_TempChart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_ValueTemp, target, "", "°C");
    }
}

void ui_event_HumidityChart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_ValueHumi, target, "", "%");
    }
}

void ui_event_LightLvRoom1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrLight1Check(e);
        _ui_slider_increment(ui_LivActiveLight, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrLight1UnCheck(e);
        _ui_slider_increment(ui_LivActiveLight, -1, LV_ANIM_ON);
    }
}

void ui_event_LightLvRoom2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrLight2Check(e);
        _ui_slider_increment(ui_LivActiveLight, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrLight2UnCheck(e);
        _ui_slider_increment(ui_BedActiveLight, -1, LV_ANIM_ON);
    }
}

void ui_event_LightLvRoom3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrLight3Check(e);
        _ui_slider_increment(ui_LivActiveLight, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrLight3UnCheck(e);
        _ui_slider_increment(ui_LivActiveLight, -1, LV_ANIM_ON);
    }
}

void ui_event_BackHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_FanLvRoom1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrFan1Check(e);
        _ui_slider_increment(ui_LivActiveFan, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrFan1UnCheck(e);
        _ui_slider_increment(ui_LivActiveFan, -1, LV_ANIM_ON);
    }
}

void ui_event_FanLvRoom2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrFan2Check(e);
        _ui_slider_increment(ui_LivActiveFan, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrFan2UnCheck(e);
        _ui_slider_increment(ui_LivActiveFan, -1, LV_ANIM_ON);
    }
}

void ui_event_ACLvRoom1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrAC1Check(e);
        _ui_slider_increment(ui_LivActiveAC, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrAC1UnCheck(e);
        _ui_slider_increment(ui_LivActiveAC, -1, LV_ANIM_ON);
    }
}

void ui_event_ACLvRoom2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrAC2Check(e);
        _ui_slider_increment(ui_LivActiveAC, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        lvrAC2UnCheck(e);
        _ui_slider_increment(ui_LivActiveAC, -1, LV_ANIM_ON);
    }
}

void ui_event_BackHome2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_BackHome3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_mainScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_FirstScreen_screen_init();
    ui_mainScreen_screen_init();
    ui_LVRoomScreen_screen_init();
    ui_BedoomSceen_screen_init();
    ui_KitchenSceen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_FirstScreen);
}
