// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Squareline

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void lvrLight1Check(lv_event_t * e);
void lvrLight1UnCheck(lv_event_t * e);
void lvrLight2Check(lv_event_t * e);
void lvrLight2UnCheck(lv_event_t * e);
void lvrLight3Check(lv_event_t * e);
void lvrLight3UnCheck(lv_event_t * e);
void lvrFan1Check(lv_event_t * e);
void lvrFan1UnCheck(lv_event_t * e);
void lvrFan2Check(lv_event_t * e);
void lvrFan2UnCheck(lv_event_t * e);
void lvrAC1Check(lv_event_t * e);
void lvrAC1UnCheck(lv_event_t * e);
void lvrAC2Check(lv_event_t * e);
void lvrAC2UnCheck(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
