// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Squareline

#include "ui.h"

void func0055(lv_event_t * e)
{
	// Your code here
}
