// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Squareline

#include "ui.h"

void func0055(lv_event_t * e){
	
}

void lvrLight1Check(lv_event_t * e)
{
	// Your code here
}

void lvrLight1UnCheck(lv_event_t * e)
{
	// Your code here
}

void lvrLight2Check(lv_event_t * e)
{
	// Your code here
}

void lvrLight2UnCheck(lv_event_t * e)
{
	// Your code here
}

void lvrLight3Check(lv_event_t * e)
{
	// Your code here
}

void lvrLight3UnCheck(lv_event_t * e)
{
	// Your code here
}

void lvrAC1Check(lv_event_t * e)
{
	// Your code here
}

void lvrAC1UnCheck(lv_event_t * e)
{
	// Your code here
}

void lvrAC2Check(lv_event_t * e)
{
	// Your code here
}

void lvrAC2UnCheck(lv_event_t * e)
{
	// Your code here
}

void lvrFan1Check(lv_event_t * e)
{
	// Your code here
}

void lvrFan1UnCheck(lv_event_t * e)
{
	// Your code here
}

void lvrFan2Check(lv_event_t * e)
{
	// Your code here
}

void lvrFan2UnCheck(lv_event_t * e)
{
	// Your code here
}
