// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Squareline

#include "../ui.h"

void ui_bedRoomScreen1_screen_init(void)
{
    ui_bedRoomScreen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_bedRoomScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_bedRoomScreen1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_bedRoomScreen1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_bedRoomScreen1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_bedRoomScreen1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_bedRoomScreen1);
    lv_obj_set_width(ui_Panel5, lv_pct(74));
    lv_obj_set_height(ui_Panel5, lv_pct(60));
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dvName3 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_dvName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dvName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dvName3, 0);
    lv_obj_set_y(ui_dvName3, -9);
    lv_obj_set_align(ui_dvName3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_dvName3, "LIGHTING");
    lv_obj_set_style_text_font(ui_dvName3, &ui_font_font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightName2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_lightName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lightName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightName2,
                      "LIGHT Bulb 1             LIGHT Bulb 2               LIGHT Bulb 3\n\n\n\n\nLIGHT Bulb 4             LIGHT Bulb5               LIGHT Bulb 6");
    lv_obj_set_style_text_font(ui_lightName2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightBedRoom1 = lv_switch_create(ui_Panel5);
    lv_obj_set_width(ui_LightBedRoom1, 100);
    lv_obj_set_height(ui_LightBedRoom1, 50);
    lv_obj_set_x(ui_LightBedRoom1, 23);
    lv_obj_set_y(ui_LightBedRoom1, 0);
    lv_obj_set_align(ui_LightBedRoom1, LV_ALIGN_LEFT_MID);

    ui_LightBedRoom2 = lv_switch_create(ui_Panel5);
    lv_obj_set_width(ui_LightBedRoom2, 100);
    lv_obj_set_height(ui_LightBedRoom2, 50);
    lv_obj_set_x(ui_LightBedRoom2, -6);
    lv_obj_set_y(ui_LightBedRoom2, 0);
    lv_obj_set_align(ui_LightBedRoom2, LV_ALIGN_CENTER);

    ui_LightBedRoom3 = lv_switch_create(ui_Panel5);
    lv_obj_set_width(ui_LightBedRoom3, 100);
    lv_obj_set_height(ui_LightBedRoom3, 50);
    lv_obj_set_x(ui_LightBedRoom3, 202);
    lv_obj_set_y(ui_LightBedRoom3, 0);
    lv_obj_set_align(ui_LightBedRoom3, LV_ALIGN_CENTER);

    ui_LightBedRoom4 = lv_switch_create(ui_Panel5);
    lv_obj_set_width(ui_LightBedRoom4, 100);
    lv_obj_set_height(ui_LightBedRoom4, 50);
    lv_obj_set_x(ui_LightBedRoom4, 23);
    lv_obj_set_y(ui_LightBedRoom4, 100);
    lv_obj_set_align(ui_LightBedRoom4, LV_ALIGN_LEFT_MID);

    ui_LightBedRoom5 = lv_switch_create(ui_Panel5);
    lv_obj_set_width(ui_LightBedRoom5, 100);
    lv_obj_set_height(ui_LightBedRoom5, 50);
    lv_obj_set_x(ui_LightBedRoom5, 0);
    lv_obj_set_y(ui_LightBedRoom5, 100);
    lv_obj_set_align(ui_LightBedRoom5, LV_ALIGN_CENTER);

    ui_LightBedRoom6 = lv_switch_create(ui_Panel5);
    lv_obj_set_width(ui_LightBedRoom6, 100);
    lv_obj_set_height(ui_LightBedRoom6, 50);
    lv_obj_set_x(ui_LightBedRoom6, 202);
    lv_obj_set_y(ui_LightBedRoom6, 100);
    lv_obj_set_align(ui_LightBedRoom6, LV_ALIGN_CENTER);

    ui_Panel6 = lv_obj_create(ui_bedRoomScreen1);
    lv_obj_set_width(ui_Panel6, lv_pct(25));
    lv_obj_set_height(ui_Panel6, lv_pct(60));
    lv_obj_set_align(ui_Panel6, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dvName4 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_dvName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dvName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dvName4, 0);
    lv_obj_set_y(ui_dvName4, -9);
    lv_obj_set_align(ui_dvName4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_dvName4, "FAN");
    lv_obj_set_style_text_font(ui_dvName4, &ui_font_font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fanName2 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_fanName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fanName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fanName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fanName2, "FAN 1\n\n\n\nFAN 2");
    lv_obj_set_style_text_font(ui_fanName2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanBedRoom1 = lv_switch_create(ui_Panel6);
    lv_obj_set_width(ui_FanBedRoom1, 100);
    lv_obj_set_height(ui_FanBedRoom1, 50);
    lv_obj_set_align(ui_FanBedRoom1, LV_ALIGN_CENTER);

    ui_FanBedRoom2 = lv_switch_create(ui_Panel6);
    lv_obj_set_width(ui_FanBedRoom2, 100);
    lv_obj_set_height(ui_FanBedRoom2, 50);
    lv_obj_set_x(ui_FanBedRoom2, 0);
    lv_obj_set_y(ui_FanBedRoom2, 100);
    lv_obj_set_align(ui_FanBedRoom2, LV_ALIGN_CENTER);

    ui_Panel7 = lv_obj_create(ui_bedRoomScreen1);
    lv_obj_set_width(ui_Panel7, lv_pct(42));
    lv_obj_set_height(ui_Panel7, lv_pct(30));
    lv_obj_set_x(ui_Panel7, lv_pct(6));
    lv_obj_set_y(ui_Panel7, lv_pct(-8));
    lv_obj_set_align(ui_Panel7, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACName3 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_ACName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ACName3, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_ACName3, "AC 1");
    lv_obj_set_style_text_font(ui_ACName3, &ui_font_font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Panel7);
    lv_slider_set_range(ui_Slider2, 16, 30);
    lv_slider_set_value(ui_Slider2, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 200);
    lv_obj_set_height(ui_Slider2, 20);

    ui_ACBedRoomTemp1 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_ACBedRoomTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACBedRoomTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ACBedRoomTemp1, 3);
    lv_obj_set_y(ui_ACBedRoomTemp1, -9);
    lv_obj_set_align(ui_ACBedRoomTemp1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_ACBedRoomTemp1, "20°C");
    lv_obj_set_style_text_font(ui_ACBedRoomTemp1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel7);
    lv_obj_set_width(ui_Switch1, 70);
    lv_obj_set_height(ui_Switch1, 35);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_BOTTOM_RIGHT);

    ui_Panel9 = lv_obj_create(ui_bedRoomScreen1);
    lv_obj_set_width(ui_Panel9, lv_pct(42));
    lv_obj_set_height(ui_Panel9, lv_pct(30));
    lv_obj_set_x(ui_Panel9, lv_pct(-6));
    lv_obj_set_y(ui_Panel9, lv_pct(-8));
    lv_obj_set_align(ui_Panel9, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACName4 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_ACName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ACName4, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_ACName4, "AC 2");
    lv_obj_set_style_text_font(ui_ACName4, &ui_font_font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider4 = lv_slider_create(ui_Panel9);
    lv_slider_set_range(ui_Slider4, 16, 30);
    lv_slider_set_value(ui_Slider4, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 200);
    lv_obj_set_height(ui_Slider4, 20);

    ui_ACBedRoomTemp2 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_ACBedRoomTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACBedRoomTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ACBedRoomTemp2, 3);
    lv_obj_set_y(ui_ACBedRoomTemp2, -9);
    lv_obj_set_align(ui_ACBedRoomTemp2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_ACBedRoomTemp2, "20°C");
    lv_obj_set_style_text_font(ui_ACBedRoomTemp2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_Panel9);
    lv_obj_set_width(ui_Switch4, 70);
    lv_obj_set_height(ui_Switch4, 35);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_BOTTOM_RIGHT);

    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider4, ui_event_Slider4, LV_EVENT_ALL, NULL);

}
