// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Squareline

#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_mainScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_mainScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_mainScreen, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_mainScreen, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lvRoom = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_lvRoom, 230);
    lv_obj_set_height(ui_lvRoom, 104);
    lv_obj_set_x(ui_lvRoom, -250);
    lv_obj_set_y(ui_lvRoom, 0);
    lv_obj_set_align(ui_lvRoom, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_lvRoom, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lvRoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomName1 = lv_label_create(ui_lvRoom);
    lv_obj_set_width(ui_roomName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_roomName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_roomName1, 0);
    lv_obj_set_y(ui_roomName1, -7);
    lv_obj_set_align(ui_roomName1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_roomName1, "LIVING ROOM");
    lv_obj_set_style_text_font(ui_roomName1, &ui_font_font32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light1 = lv_label_create(ui_lvRoom);
    lv_obj_set_width(ui_light1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_light1, -37);
    lv_obj_set_y(ui_light1, 1);
    lv_obj_set_align(ui_light1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_light1, "LIGHT       3/4 ON");
    lv_obj_set_style_text_align(ui_light1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fan1 = lv_label_create(ui_lvRoom);
    lv_obj_set_width(ui_fan1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fan1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fan1, -37);
    lv_obj_set_y(ui_fan1, 17);
    lv_obj_set_align(ui_fan1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_fan1, "FAN       0/2 ON");

    ui_ac1 = lv_label_create(ui_lvRoom);
    lv_obj_set_width(ui_ac1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ac1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ac1, -37);
    lv_obj_set_y(ui_ac1, 33);
    lv_obj_set_align(ui_ac1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ac1, "AC        0/1 ON");

    ui_kitchenRoom = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_kitchenRoom, 230);
    lv_obj_set_height(ui_kitchenRoom, 104);
    lv_obj_set_align(ui_kitchenRoom, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_kitchenRoom, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_kitchenRoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomName4 = lv_label_create(ui_kitchenRoom);
    lv_obj_set_width(ui_roomName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_roomName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_roomName4, 0);
    lv_obj_set_y(ui_roomName4, -7);
    lv_obj_set_align(ui_roomName4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_roomName4, "KITCHEN");
    lv_obj_set_style_text_font(ui_roomName4, &ui_font_font32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light4 = lv_label_create(ui_kitchenRoom);
    lv_obj_set_width(ui_light4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_light4, -37);
    lv_obj_set_y(ui_light4, 1);
    lv_obj_set_align(ui_light4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_light4, "LIGHT       0/6 ON");
    lv_obj_set_style_text_align(ui_light4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fan4 = lv_label_create(ui_kitchenRoom);
    lv_obj_set_width(ui_fan4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fan4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fan4, -37);
    lv_obj_set_y(ui_fan4, 17);
    lv_obj_set_align(ui_fan4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_fan4, "FAN       0/2 ON");

    ui_ac4 = lv_label_create(ui_kitchenRoom);
    lv_obj_set_width(ui_ac4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ac4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ac4, -37);
    lv_obj_set_y(ui_ac4, 33);
    lv_obj_set_align(ui_ac4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ac4, "AC        0/1 ON");

    ui_bedRoom1 = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_bedRoom1, 230);
    lv_obj_set_height(ui_bedRoom1, 104);
    lv_obj_set_x(ui_bedRoom1, -250);
    lv_obj_set_y(ui_bedRoom1, 125);
    lv_obj_set_align(ui_bedRoom1, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_bedRoom1, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bedRoom1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomName2 = lv_label_create(ui_bedRoom1);
    lv_obj_set_width(ui_roomName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_roomName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_roomName2, 0);
    lv_obj_set_y(ui_roomName2, -7);
    lv_obj_set_align(ui_roomName2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_roomName2, "BEDROOM 1");
    lv_obj_set_style_text_font(ui_roomName2, &ui_font_font32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light2 = lv_label_create(ui_bedRoom1);
    lv_obj_set_width(ui_light2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_light2, -37);
    lv_obj_set_y(ui_light2, 1);
    lv_obj_set_align(ui_light2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_light2, "LIGHT       0/6 ON");
    lv_obj_set_style_text_align(ui_light2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fan2 = lv_label_create(ui_bedRoom1);
    lv_obj_set_width(ui_fan2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fan2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fan2, -37);
    lv_obj_set_y(ui_fan2, 17);
    lv_obj_set_align(ui_fan2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_fan2, "FAN       0/2 ON");

    ui_ac2 = lv_label_create(ui_bedRoom1);
    lv_obj_set_width(ui_ac2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ac2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ac2, -37);
    lv_obj_set_y(ui_ac2, 33);
    lv_obj_set_align(ui_ac2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ac2, "AC        0/1 ON");

    ui_bedRoom2 = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_bedRoom2, 230);
    lv_obj_set_height(ui_bedRoom2, 104);
    lv_obj_set_x(ui_bedRoom2, 0);
    lv_obj_set_y(ui_bedRoom2, 125);
    lv_obj_set_align(ui_bedRoom2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_bedRoom2, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bedRoom2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomName3 = lv_label_create(ui_bedRoom2);
    lv_obj_set_width(ui_roomName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_roomName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_roomName3, 0);
    lv_obj_set_y(ui_roomName3, -7);
    lv_obj_set_align(ui_roomName3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_roomName3, "BEDROOM 2");
    lv_obj_set_style_text_font(ui_roomName3, &ui_font_font32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light3 = lv_label_create(ui_bedRoom2);
    lv_obj_set_width(ui_light3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_light3, -37);
    lv_obj_set_y(ui_light3, 1);
    lv_obj_set_align(ui_light3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_light3, "LIGHT       0/6 ON");
    lv_obj_set_style_text_align(ui_light3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fan3 = lv_label_create(ui_bedRoom2);
    lv_obj_set_width(ui_fan3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fan3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fan3, -37);
    lv_obj_set_y(ui_fan3, 17);
    lv_obj_set_align(ui_fan3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_fan3, "FAN       0/2 ON");

    ui_ac3 = lv_label_create(ui_bedRoom2);
    lv_obj_set_width(ui_ac3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ac3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ac3, -37);
    lv_obj_set_y(ui_ac3, 33);
    lv_obj_set_align(ui_ac3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ac3, "AC        0/1 ON");

    ui_bedRoom3 = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_bedRoom3, 230);
    lv_obj_set_height(ui_bedRoom3, 104);
    lv_obj_set_x(ui_bedRoom3, 0);
    lv_obj_set_y(ui_bedRoom3, 250);
    lv_obj_set_align(ui_bedRoom3, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_bedRoom3, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bedRoom3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomName5 = lv_label_create(ui_bedRoom3);
    lv_obj_set_width(ui_roomName5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_roomName5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_roomName5, 0);
    lv_obj_set_y(ui_roomName5, -7);
    lv_obj_set_align(ui_roomName5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_roomName5, "BEDROOM 2");
    lv_obj_set_style_text_font(ui_roomName5, &ui_font_font32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light5 = lv_label_create(ui_bedRoom3);
    lv_obj_set_width(ui_light5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_light5, -37);
    lv_obj_set_y(ui_light5, 1);
    lv_obj_set_align(ui_light5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_light5, "LIGHT       0/6 ON");
    lv_obj_set_style_text_align(ui_light5, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fan5 = lv_label_create(ui_bedRoom3);
    lv_obj_set_width(ui_fan5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fan5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fan5, -37);
    lv_obj_set_y(ui_fan5, 17);
    lv_obj_set_align(ui_fan5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_fan5, "FAN       0/2 ON");

    ui_ac5 = lv_label_create(ui_bedRoom3);
    lv_obj_set_width(ui_ac5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ac5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ac5, -37);
    lv_obj_set_y(ui_ac5, 33);
    lv_obj_set_align(ui_ac5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ac5, "AC        0/1 ON");

    ui_eTemp = lv_arc_create(ui_mainScreen);
    lv_obj_set_width(ui_eTemp, 200);
    lv_obj_set_height(ui_eTemp, 200);
    lv_arc_set_range(ui_eTemp, 0, 40);
    lv_arc_set_value(ui_eTemp, 16);
    lv_arc_set_bg_angles(ui_eTemp, 0, 360);
    lv_arc_set_rotation(ui_eTemp, 180);

    ui_envTemp = lv_label_create(ui_eTemp);
    lv_obj_set_width(ui_envTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_envTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_envTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_envTemp, "16°C");
    lv_obj_set_style_text_font(ui_envTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eHumi = lv_arc_create(ui_mainScreen);
    lv_obj_set_width(ui_eHumi, 200);
    lv_obj_set_height(ui_eHumi, 200);
    lv_obj_set_x(ui_eHumi, 0);
    lv_obj_set_y(ui_eHumi, -19);
    lv_obj_set_align(ui_eHumi, LV_ALIGN_BOTTOM_LEFT);
    lv_arc_set_value(ui_eHumi, 70);
    lv_arc_set_bg_angles(ui_eHumi, 0, 360);
    lv_arc_set_rotation(ui_eHumi, 180);

    ui_envHumi = lv_label_create(ui_eHumi);
    lv_obj_set_width(ui_envHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_envHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_envHumi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_envHumi, "70%");
    lv_obj_set_style_text_font(ui_envHumi, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_eTemp, ui_event_eTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_eHumi, ui_event_eHumi, LV_EVENT_ALL, NULL);

}
