// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Squareline

#ifndef UI_BEDOOMSCEEN_H
#define UI_BEDOOMSCEEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BedoomSceen
extern void ui_BedoomSceen_screen_init(void);
extern void ui_BedoomSceen_screen_destroy(void);
extern lv_obj_t * ui_BedoomSceen;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_dvName3;
extern lv_obj_t * ui_LightBedRoom1;
extern lv_obj_t * ui_LightBedRoom2;
extern lv_obj_t * ui_LightBedRoom3;
extern void ui_event_BackHome2(lv_event_t * e);
extern lv_obj_t * ui_BackHome2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_dvName4;
extern lv_obj_t * ui_FanBedRoom1;
extern lv_obj_t * ui_FanBedRoom2;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_ACName3;
extern lv_obj_t * ui_ACBedRoom1;
extern lv_obj_t * ui_Lightbed1;
extern lv_obj_t * ui_Lightbed2;
extern lv_obj_t * ui_Lightbed3;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

