// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Squareline

#include "../ui.h"

void ui_BedoomSceen_screen_init(void)
{
    ui_BedoomSceen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BedoomSceen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_BedoomSceen, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BedoomSceen, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BedoomSceen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BedoomSceen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_BedoomSceen);
    lv_obj_set_width(ui_Panel5, lv_pct(74));
    lv_obj_set_height(ui_Panel5, lv_pct(45));
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x4D8E13), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dvName3 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_dvName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dvName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dvName3, 30);
    lv_obj_set_y(ui_dvName3, -9);
    lv_obj_set_align(ui_dvName3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_dvName3, "BED ROOM ");
    lv_obj_set_style_text_color(ui_dvName3, lv_color_hex(0xD1F100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dvName3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dvName3, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightBedRoom1 = lv_switch_create(ui_Panel5);
    lv_obj_set_width(ui_LightBedRoom1, 100);
    lv_obj_set_height(ui_LightBedRoom1, 50);
    lv_obj_set_x(ui_LightBedRoom1, 10);
    lv_obj_set_y(ui_LightBedRoom1, 38);
    lv_obj_set_align(ui_LightBedRoom1, LV_ALIGN_LEFT_MID);

    ui_LightBedRoom2 = lv_switch_create(ui_Panel5);
    lv_obj_set_width(ui_LightBedRoom2, 100);
    lv_obj_set_height(ui_LightBedRoom2, 50);
    lv_obj_set_x(ui_LightBedRoom2, 208);
    lv_obj_set_y(ui_LightBedRoom2, 38);
    lv_obj_set_align(ui_LightBedRoom2, LV_ALIGN_LEFT_MID);

    ui_LightBedRoom3 = lv_switch_create(ui_Panel5);
    lv_obj_set_width(ui_LightBedRoom3, 100);
    lv_obj_set_height(ui_LightBedRoom3, 50);
    lv_obj_set_x(ui_LightBedRoom3, 422);
    lv_obj_set_y(ui_LightBedRoom3, 37);
    lv_obj_set_align(ui_LightBedRoom3, LV_ALIGN_LEFT_MID);

    ui_BackHome2 = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_BackHome2, 50);
    lv_obj_set_height(ui_BackHome2, 50);
    lv_obj_set_x(ui_BackHome2, -235);
    lv_obj_set_y(ui_BackHome2, -59);
    lv_obj_set_align(ui_BackHome2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BackHome2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackHome2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackHome2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_BackHome2);
    lv_img_set_src(ui_Image2, &ui_img_1385603933);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image2, -1);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_BedoomSceen);
    lv_obj_set_width(ui_Panel6, lv_pct(25));
    lv_obj_set_height(ui_Panel6, lv_pct(70));
    lv_obj_set_align(ui_Panel6, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dvName4 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_dvName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dvName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dvName4, 0);
    lv_obj_set_y(ui_dvName4, -9);
    lv_obj_set_align(ui_dvName4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_dvName4, "FAN");
    lv_obj_set_style_text_font(ui_dvName4, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanBedRoom1 = lv_switch_create(ui_Panel6);
    lv_obj_set_width(ui_FanBedRoom1, 100);
    lv_obj_set_height(ui_FanBedRoom1, 50);
    lv_obj_set_x(ui_FanBedRoom1, 0);
    lv_obj_set_y(ui_FanBedRoom1, -9);
    lv_obj_set_align(ui_FanBedRoom1, LV_ALIGN_CENTER);

    ui_FanBedRoom2 = lv_switch_create(ui_Panel6);
    lv_obj_set_width(ui_FanBedRoom2, 100);
    lv_obj_set_height(ui_FanBedRoom2, 50);
    lv_obj_set_x(ui_FanBedRoom2, 0);
    lv_obj_set_y(ui_FanBedRoom2, 95);
    lv_obj_set_align(ui_FanBedRoom2, LV_ALIGN_CENTER);

    ui_Panel7 = lv_obj_create(ui_BedoomSceen);
    lv_obj_set_width(ui_Panel7, lv_pct(34));
    lv_obj_set_height(ui_Panel7, lv_pct(18));
    lv_obj_set_x(ui_Panel7, lv_pct(0));
    lv_obj_set_y(ui_Panel7, lv_pct(48));
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACName3 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_ACName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ACName3, -84);
    lv_obj_set_y(ui_ACName3, 2);
    lv_obj_set_align(ui_ACName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ACName3, "Air 1");
    lv_obj_set_style_text_font(ui_ACName3, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACBedRoom1 = lv_switch_create(ui_Panel7);
    lv_obj_set_width(ui_ACBedRoom1, 70);
    lv_obj_set_height(ui_ACBedRoom1, 35);
    lv_obj_set_x(ui_ACBedRoom1, 0);
    lv_obj_set_y(ui_ACBedRoom1, 3);
    lv_obj_set_align(ui_ACBedRoom1, LV_ALIGN_BOTTOM_RIGHT);

    ui_Lightbed1 = lv_label_create(ui_BedoomSceen);
    lv_obj_set_width(ui_Lightbed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lightbed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lightbed1, -296);
    lv_obj_set_y(ui_Lightbed1, -123);
    lv_obj_set_align(ui_Lightbed1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lightbed1, "LIGHT Bulb 1");
    lv_obj_set_style_text_font(ui_Lightbed1, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lightbed2 = lv_label_create(ui_BedoomSceen);
    lv_obj_set_width(ui_Lightbed2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lightbed2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lightbed2, -98);
    lv_obj_set_y(ui_Lightbed2, -123);
    lv_obj_set_align(ui_Lightbed2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lightbed2, "LIGHT Bulb 2");
    lv_obj_set_style_text_font(ui_Lightbed2, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lightbed3 = lv_label_create(ui_BedoomSceen);
    lv_obj_set_width(ui_Lightbed3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lightbed3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lightbed3, 110);
    lv_obj_set_y(ui_Lightbed3, -123);
    lv_obj_set_align(ui_Lightbed3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lightbed3, "LIGHT Bulb 3");
    lv_obj_set_style_text_font(ui_Lightbed3, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_BedoomSceen);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 285);
    lv_obj_set_y(ui_Label14, -118);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "FAN 1");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_BedoomSceen);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 289);
    lv_obj_set_y(ui_Label15, -19);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "FAN 2");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BackHome2, ui_event_BackHome2, LV_EVENT_ALL, NULL);

}
