// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Squareline

#ifndef UI_INITIAL_SCREEN_H
#define UI_INITIAL_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Initial_Screen
extern void ui_Initial_Screen_screen_init(void);
extern void ui_Initial_Screen_screen_destroy(void);
extern lv_obj_t * ui_Initial_Screen;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Title_scr;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

