// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Squareline

#include "../ui.h"

lv_obj_t * ui_Initial_Screen;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Title_scr;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label3;

// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SetingWifi, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SetingWifi_screen_init);
    }
}

// build funtions

void ui_Initial_Screen_screen_init(void)
{
    ui_Initial_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Initial_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Initial_Screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Initial_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Initial_Screen);
    lv_img_set_src(ui_Image5, &ui_img_hcmut_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 271
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 276
    lv_obj_set_x(ui_Image5, 1);
    lv_obj_set_y(ui_Image5, -130);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 150);

    ui_Title_scr = lv_label_create(ui_Initial_Screen);
    lv_obj_set_width(ui_Title_scr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title_scr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title_scr, 8);
    lv_obj_set_y(ui_Title_scr, 18);
    lv_obj_set_align(ui_Title_scr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Title_scr, "BK SMART HOME IOT");
    lv_obj_set_style_text_color(ui_Title_scr, lv_color_hex(0x050977), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Title_scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Title_scr, &ui_font_Font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Initial_Screen);
    lv_obj_set_width(ui_Button1, 187);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 4);
    lv_obj_set_y(ui_Button1, 95);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, -1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Next to screen");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Initial_Screen_screen_destroy(void)
{
    if(ui_Initial_Screen) lv_obj_del(ui_Initial_Screen);

    // NULL screen variables
    ui_Initial_Screen = NULL;
    ui_Image5 = NULL;
    ui_Title_scr = NULL;
    ui_Button1 = NULL;
    ui_Label3 = NULL;

}
