// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Squareline

#include "../ui.h"

void ui_LVRoomScreen_screen_init(void)
{
    ui_LVRoomScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LVRoomScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_LVRoomScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LVRoomScreen, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LVRoomScreen, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LVRoomScreen, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LVRoomScreen, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_Panel2, lv_pct(74));
    lv_obj_set_height(ui_Panel2, lv_pct(45));
    lv_obj_set_x(ui_Panel2, -101);
    lv_obj_set_y(ui_Panel2, -15);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x4D8E13), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dvName1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_dvName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dvName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dvName1, 23);
    lv_obj_set_y(ui_dvName1, -9);
    lv_obj_set_align(ui_dvName1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_dvName1, "LIVING ROOM");
    lv_obj_set_style_text_color(ui_dvName1, lv_color_hex(0xD1F100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dvName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dvName1, &ui_font_font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightName1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lightName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightName1, -4);
    lv_obj_set_y(ui_lightName1, 37);
    lv_obj_set_align(ui_lightName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightName1, "LIGHT Bulb 1             LIGHT Bulb 2               LIGHT Bulb  3\n\n\n\n");
    lv_obj_set_style_text_font(ui_lightName1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLvRoom1 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_LightLvRoom1, 100);
    lv_obj_set_height(ui_LightLvRoom1, 50);
    lv_obj_set_x(ui_LightLvRoom1, 3);
    lv_obj_set_y(ui_LightLvRoom1, 84);

    ui_LightLvRoom2 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_LightLvRoom2, 100);
    lv_obj_set_height(ui_LightLvRoom2, 50);
    lv_obj_set_x(ui_LightLvRoom2, 201);
    lv_obj_set_y(ui_LightLvRoom2, 84);

    ui_LightLvRoom3 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_LightLvRoom3, 100);
    lv_obj_set_height(ui_LightLvRoom3, 50);
    lv_obj_set_x(ui_LightLvRoom3, 409);
    lv_obj_set_y(ui_LightLvRoom3, 83);

    ui_BackHome = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_BackHome, 50);
    lv_obj_set_height(ui_BackHome, 50);
    lv_obj_set_x(ui_BackHome, -243);
    lv_obj_set_y(ui_BackHome, -55);
    lv_obj_set_align(ui_BackHome, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BackHome, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_BackHome);
    lv_img_set_src(ui_Image4, &ui_img_1385603933);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image4, -1);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_Panel3, lv_pct(25));
    lv_obj_set_height(ui_Panel3, lv_pct(70));
    lv_obj_set_x(ui_Panel3, 9);
    lv_obj_set_y(ui_Panel3, -15);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dvName2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_dvName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dvName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dvName2, 0);
    lv_obj_set_y(ui_dvName2, -9);
    lv_obj_set_align(ui_dvName2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_dvName2, "FAN");
    lv_obj_set_style_text_font(ui_dvName2, &ui_font_font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fanName1 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_fanName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fanName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fanName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fanName1, "FAN 1\n\n\n\n\nFAN 2");
    lv_obj_set_style_text_font(ui_fanName1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanLvRoom1 = lv_switch_create(ui_Panel3);
    lv_obj_set_width(ui_FanLvRoom1, 100);
    lv_obj_set_height(ui_FanLvRoom1, 50);
    lv_obj_set_align(ui_FanLvRoom1, LV_ALIGN_CENTER);

    ui_FanLvRoom2 = lv_switch_create(ui_Panel3);
    lv_obj_set_width(ui_FanLvRoom2, 100);
    lv_obj_set_height(ui_FanLvRoom2, 50);
    lv_obj_set_x(ui_FanLvRoom2, 0);
    lv_obj_set_y(ui_FanLvRoom2, 100);
    lv_obj_set_align(ui_FanLvRoom2, LV_ALIGN_CENTER);

    ui_Panel4 = lv_obj_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_Panel4, lv_pct(50));
    lv_obj_set_height(ui_Panel4, lv_pct(23));
    lv_obj_set_x(ui_Panel4, lv_pct(0));
    lv_obj_set_y(ui_Panel4, lv_pct(45));
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACName1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_ACName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ACName1, 5);
    lv_obj_set_y(ui_ACName1, -2);
    lv_label_set_text(ui_ACName1, "Air 1");
    lv_obj_set_style_text_font(ui_ACName1, &ui_font_font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Panel4);
    lv_obj_set_width(ui_Switch2, 70);
    lv_obj_set_height(ui_Switch2, 35);
    lv_obj_set_x(ui_Switch2, 4);
    lv_obj_set_y(ui_Switch2, -8);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_BOTTOM_RIGHT);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_Panel8, lv_pct(50));
    lv_obj_set_height(ui_Panel8, lv_pct(23));
    lv_obj_set_x(ui_Panel8, lv_pct(0));
    lv_obj_set_y(ui_Panel8, lv_pct(71));
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACName2 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_ACName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ACName2, 8);
    lv_obj_set_y(ui_ACName2, -1);
    lv_label_set_text(ui_ACName2, "Air 2");
    lv_obj_set_style_text_font(ui_ACName2, &ui_font_font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel8);
    lv_obj_set_width(ui_Switch1, 70);
    lv_obj_set_height(ui_Switch1, 35);
    lv_obj_set_x(ui_Switch1, 4);
    lv_obj_set_y(ui_Switch1, -8);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_BOTTOM_RIGHT);

    lv_obj_add_event_cb(ui_LightLvRoom1, ui_event_LightLvRoom1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LightLvRoom2, ui_event_LightLvRoom2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LightLvRoom3, ui_event_LightLvRoom3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackHome, ui_event_BackHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FanLvRoom1, ui_event_FanLvRoom1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FanLvRoom2, ui_event_FanLvRoom2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);

}
