// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Squareline

#include "../ui.h"

lv_obj_t *ui_LVRoomScreen;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_dvName1;
lv_obj_t *ui_LightLvRoom1;
lv_obj_t *ui_LightLvRoom2;
lv_obj_t *ui_LightLvRoom3;
lv_obj_t *ui_BackHome;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_dvName2;
lv_obj_t *ui_FanLvRoom1;
lv_obj_t *ui_FanLvRoom2;
lv_obj_t *ui_Fan1;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_ACName1;
lv_obj_t *ui_Switch2;
lv_obj_t *ui_LIGHT_Bulb_1_;
lv_obj_t *ui_LIGHT_Bulb_2;
lv_obj_t *ui_LIGHT_Bulb_3;
lv_obj_t *ui_Fan2;

// event funtions
void ui_event_LightLvRoom1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        LvR_light1(e);
    }
}

void ui_event_LightLvRoom2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        LvR_light2(e);
    }
}

void ui_event_LightLvRoom3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        LvR_light3(e);
    }
}

void ui_event_BackHome(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_FanLvRoom1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        LvR_fan1(e);
    }
}

void ui_event_FanLvRoom2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        LvR_fan2(e);
    }
}

void ui_event_Switch2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        LvR_air1(e);
    }
}

// build funtions

void ui_LVRoomScreen_screen_init(void)
{
    ui_LVRoomScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LVRoomScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_grad_dir(ui_LVRoomScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LVRoomScreen, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LVRoomScreen, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LVRoomScreen, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LVRoomScreen, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_Panel2, lv_pct(74));
    lv_obj_set_height(ui_Panel2, lv_pct(45));
    lv_obj_set_x(ui_Panel2, -101);
    lv_obj_set_y(ui_Panel2, -15);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x4D8E13), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dvName1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_dvName1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_dvName1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_dvName1, 23);
    lv_obj_set_y(ui_dvName1, -9);
    lv_obj_set_align(ui_dvName1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_dvName1, "LIVING ROOM");
    lv_obj_set_style_text_color(ui_dvName1, lv_color_hex(0xD1F100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dvName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dvName1, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLvRoom1 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_LightLvRoom1, 100);
    lv_obj_set_height(ui_LightLvRoom1, 50);
    lv_obj_set_x(ui_LightLvRoom1, 3);
    lv_obj_set_y(ui_LightLvRoom1, 84);

    ui_LightLvRoom2 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_LightLvRoom2, 100);
    lv_obj_set_height(ui_LightLvRoom2, 50);
    lv_obj_set_x(ui_LightLvRoom2, 201);
    lv_obj_set_y(ui_LightLvRoom2, 84);

    ui_LightLvRoom3 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_LightLvRoom3, 100);
    lv_obj_set_height(ui_LightLvRoom3, 50);
    lv_obj_set_x(ui_LightLvRoom3, 409);
    lv_obj_set_y(ui_LightLvRoom3, 83);

    ui_BackHome = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_BackHome, 50);
    lv_obj_set_height(ui_BackHome, 50);
    lv_obj_set_x(ui_BackHome, -243);
    lv_obj_set_y(ui_BackHome, -55);
    lv_obj_set_align(ui_BackHome, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BackHome, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_BackHome);
    lv_img_set_src(ui_Image4, &ui_img_1385603933);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);  /// 25
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT); /// 25
    lv_obj_set_x(ui_Image4, -1);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Panel3 = lv_obj_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_Panel3, lv_pct(25));
    lv_obj_set_height(ui_Panel3, lv_pct(70));
    lv_obj_set_x(ui_Panel3, 2);
    lv_obj_set_y(ui_Panel3, -16);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dvName2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_dvName2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_dvName2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_dvName2, 0);
    lv_obj_set_y(ui_dvName2, -9);
    lv_obj_set_align(ui_dvName2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_dvName2, "FAN");
    lv_obj_set_style_text_font(ui_dvName2, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanLvRoom1 = lv_switch_create(ui_Panel3);
    lv_obj_set_width(ui_FanLvRoom1, 100);
    lv_obj_set_height(ui_FanLvRoom1, 50);
    lv_obj_set_align(ui_FanLvRoom1, LV_ALIGN_CENTER);

    ui_FanLvRoom2 = lv_switch_create(ui_Panel3);
    lv_obj_set_width(ui_FanLvRoom2, 100);
    lv_obj_set_height(ui_FanLvRoom2, 50);
    lv_obj_set_x(ui_FanLvRoom2, 0);
    lv_obj_set_y(ui_FanLvRoom2, 100);
    lv_obj_set_align(ui_FanLvRoom2, LV_ALIGN_CENTER);

    ui_Fan1 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Fan1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Fan1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Fan1, -2);
    lv_obj_set_y(ui_Fan1, -57);
    lv_obj_set_align(ui_Fan1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan1, "FAN 1");
    lv_obj_set_style_text_font(ui_Fan1, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_Panel4, lv_pct(34));
    lv_obj_set_height(ui_Panel4, lv_pct(19));
    lv_obj_set_x(ui_Panel4, lv_pct(0));
    lv_obj_set_y(ui_Panel4, lv_pct(45));
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACName1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_ACName1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ACName1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ACName1, -1);
    lv_obj_set_y(ui_ACName1, -3);
    lv_label_set_text(ui_ACName1, "Air 1");
    lv_obj_set_style_text_font(ui_ACName1, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Panel4);
    lv_obj_set_width(ui_Switch2, 70);
    lv_obj_set_height(ui_Switch2, 35);
    lv_obj_set_x(ui_Switch2, -1);
    lv_obj_set_y(ui_Switch2, 0);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_BOTTOM_RIGHT);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LIGHT_Bulb_1_ = lv_label_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_LIGHT_Bulb_1_, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LIGHT_Bulb_1_, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LIGHT_Bulb_1_, -305);
    lv_obj_set_y(ui_LIGHT_Bulb_1_, -127);
    lv_obj_set_align(ui_LIGHT_Bulb_1_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LIGHT_Bulb_1_, "LIGHT Bulb 1 ");
    lv_obj_set_style_text_font(ui_LIGHT_Bulb_1_, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LIGHT_Bulb_2 = lv_label_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_LIGHT_Bulb_2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LIGHT_Bulb_2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LIGHT_Bulb_2, -114);
    lv_obj_set_y(ui_LIGHT_Bulb_2, -128);
    lv_obj_set_align(ui_LIGHT_Bulb_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LIGHT_Bulb_2, "LIGHT Bulb 2");
    lv_obj_set_style_text_font(ui_LIGHT_Bulb_2, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LIGHT_Bulb_3 = lv_label_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_LIGHT_Bulb_3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LIGHT_Bulb_3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LIGHT_Bulb_3, 100);
    lv_obj_set_y(ui_LIGHT_Bulb_3, -129);
    lv_obj_set_align(ui_LIGHT_Bulb_3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LIGHT_Bulb_3, "LIGHT Bulb 3");
    lv_obj_set_style_text_font(ui_LIGHT_Bulb_3, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan2 = lv_label_create(ui_LVRoomScreen);
    lv_obj_set_width(ui_Fan2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Fan2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Fan2, 294);
    lv_obj_set_y(ui_Fan2, -24);
    lv_obj_set_align(ui_Fan2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan2, "FAN 2");
    lv_obj_set_style_text_font(ui_Fan2, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LightLvRoom1, ui_event_LightLvRoom1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LightLvRoom2, ui_event_LightLvRoom2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LightLvRoom3, ui_event_LightLvRoom3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackHome, ui_event_BackHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FanLvRoom1, ui_event_FanLvRoom1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FanLvRoom2, ui_event_FanLvRoom2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
}

void ui_LVRoomScreen_screen_destroy(void)
{
    if (ui_LVRoomScreen)
        lv_obj_del(ui_LVRoomScreen);

    // NULL screen variables
    ui_LVRoomScreen = NULL;
    ui_Panel2 = NULL;
    ui_dvName1 = NULL;
    ui_LightLvRoom1 = NULL;
    ui_LightLvRoom2 = NULL;
    ui_LightLvRoom3 = NULL;
    ui_BackHome = NULL;
    ui_Image4 = NULL;
    ui_Panel3 = NULL;
    ui_dvName2 = NULL;
    ui_FanLvRoom1 = NULL;
    ui_FanLvRoom2 = NULL;
    ui_Fan1 = NULL;
    ui_Panel4 = NULL;
    ui_ACName1 = NULL;
    ui_Switch2 = NULL;
    ui_LIGHT_Bulb_1_ = NULL;
    ui_LIGHT_Bulb_2 = NULL;
    ui_LIGHT_Bulb_3 = NULL;
    ui_Fan2 = NULL;
}
