// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Squareline

#ifndef UI_LVROOMSCREEN_H
#define UI_LVROOMSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LVRoomScreen
extern void ui_LVRoomScreen_screen_init(void);
extern void ui_LVRoomScreen_screen_destroy(void);
extern lv_obj_t * ui_LVRoomScreen;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_dvName1;
extern void ui_event_LightLvRoom1(lv_event_t * e);
extern lv_obj_t * ui_LightLvRoom1;
extern void ui_event_LightLvRoom2(lv_event_t * e);
extern lv_obj_t * ui_LightLvRoom2;
extern void ui_event_LightLvRoom3(lv_event_t * e);
extern lv_obj_t * ui_LightLvRoom3;
extern void ui_event_BackHome(lv_event_t * e);
extern lv_obj_t * ui_BackHome;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_dvName2;
extern void ui_event_FanLvRoom1(lv_event_t * e);
extern lv_obj_t * ui_FanLvRoom1;
extern void ui_event_FanLvRoom2(lv_event_t * e);
extern lv_obj_t * ui_FanLvRoom2;
extern lv_obj_t * ui_Fan1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_ACName1;
extern void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_LIGHT_Bulb_1_;
extern lv_obj_t * ui_LIGHT_Bulb_2;
extern lv_obj_t * ui_LIGHT_Bulb_3;
extern lv_obj_t * ui_Fan2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

