// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Squareline

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabView2;
extern void ui_event_BedRoom(lv_event_t * e);
extern lv_obj_t * ui_BedRoom;
extern lv_obj_t * ui_roomName4;
extern lv_obj_t * ui_LightBedRoom;
extern lv_obj_t * ui_FanBedRoom;
extern lv_obj_t * ui_AirBedRoom;
extern lv_obj_t * ui_titleComp1;
extern lv_obj_t * ui_BedActiveLight;
extern lv_obj_t * ui_BedActiveFan;
extern lv_obj_t * ui_BedActiveAC;
extern lv_obj_t * ui_CountLightB;
extern lv_obj_t * ui_CountFanB;
extern lv_obj_t * ui_CountACB;
extern void ui_event_LvRoom(lv_event_t * e);
extern lv_obj_t * ui_LvRoom;
extern lv_obj_t * ui_roomName1;
extern lv_obj_t * ui_LightLvRoom;
extern lv_obj_t * ui_FanLvRoom;
extern lv_obj_t * ui_AirLvRoom;
extern lv_obj_t * ui_titleComp;
extern lv_obj_t * ui_LivActiveLight;
extern lv_obj_t * ui_CountLightLV;
extern lv_obj_t * ui_LivActiveFan;
extern lv_obj_t * ui_CountFanLV;
extern lv_obj_t * ui_LivActiveAC;
extern lv_obj_t * ui_CountACLV;
extern void ui_event_TempChart(lv_event_t * e);
extern lv_obj_t * ui_TempChart;
extern lv_obj_t * ui_TitleTemp;
extern lv_obj_t * ui_ValueTemp;
extern void ui_event_HumidityChart(lv_event_t * e);
extern lv_obj_t * ui_HumidityChart;
extern lv_obj_t * ui_TitleHumi;
extern lv_obj_t * ui_ValueHumi;
extern lv_obj_t * ui_HeaedMain;
extern lv_obj_t * ui_TitleVIEW;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

