// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Squareline

#include "../ui.h"

lv_obj_t * ui_mainScreen;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabView2;
lv_obj_t * ui_BedRoom;
lv_obj_t * ui_roomName4;
lv_obj_t * ui_LightBedRoom;
lv_obj_t * ui_FanBedRoom;
lv_obj_t * ui_AirBedRoom;
lv_obj_t * ui_titleComp1;
lv_obj_t * ui_BedActiveLight;
lv_obj_t * ui_BedActiveFan;
lv_obj_t * ui_BedActiveAC;
lv_obj_t * ui_CountLightB;
lv_obj_t * ui_CountFanB;
lv_obj_t * ui_CountACB;
lv_obj_t * ui_LvRoom;
lv_obj_t * ui_roomName1;
lv_obj_t * ui_LightLvRoom;
lv_obj_t * ui_FanLvRoom;
lv_obj_t * ui_AirLvRoom;
lv_obj_t * ui_titleComp;
lv_obj_t * ui_LivActiveLight;
lv_obj_t * ui_CountLightLV;
lv_obj_t * ui_LivActiveFan;
lv_obj_t * ui_CountFanLV;
lv_obj_t * ui_LivActiveAC;
lv_obj_t * ui_CountACLV;
lv_obj_t * ui_TempChart;
lv_obj_t * ui_TitleTemp;
lv_obj_t * ui_ValueTemp;
lv_obj_t * ui_HumidityChart;
lv_obj_t * ui_TitleHumi;
lv_obj_t * ui_ValueHumi;
lv_obj_t * ui_HeaedMain;
lv_obj_t * ui_TitleVIEW;

// event funtions
void ui_event_BedRoom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BedoomSceen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_BedoomSceen_screen_init);
    }
}

void ui_event_LvRoom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LVRoomScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_LVRoomScreen_screen_init);
    }
}

void ui_event_TempChart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_ValueTemp, target, "", "°C");
    }
}

void ui_event_HumidityChart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_ValueHumi, target, "", "%");
    }
}

// build funtions

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_mainScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_mainScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_mainScreen, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_mainScreen, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_mainScreen, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 540);
    lv_obj_set_height(ui_TabView1, 452);
    lv_obj_set_x(ui_TabView1, 215);
    lv_obj_set_y(ui_TabView1, -28);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TabView1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xBCCCDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_TabView1), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xE1DEF8),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView2 = lv_tabview_create(ui_mainScreen, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView2, 218);
    lv_obj_set_height(ui_TabView2, 452);
    lv_obj_set_x(ui_TabView2, -14);
    lv_obj_set_y(ui_TabView2, -28);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TabView2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabView2, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedRoom = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_BedRoom, 250);
    lv_obj_set_height(ui_BedRoom, 160);
    lv_obj_set_x(ui_BedRoom, -2);
    lv_obj_set_y(ui_BedRoom, 34);
    lv_obj_set_align(ui_BedRoom, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_BedRoom, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BedRoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BedRoom, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BedRoom, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BedRoom, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BedRoom, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomName4 = lv_label_create(ui_BedRoom);
    lv_obj_set_width(ui_roomName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_roomName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_roomName4, 2);
    lv_obj_set_y(ui_roomName4, 4);
    lv_obj_set_align(ui_roomName4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_roomName4, "BED ROOM");
    lv_obj_set_style_text_font(ui_roomName4, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightBedRoom = lv_label_create(ui_BedRoom);
    lv_obj_set_width(ui_LightBedRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightBedRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightBedRoom, -1);
    lv_obj_set_y(ui_LightBedRoom, 5);
    lv_obj_set_align(ui_LightBedRoom, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LightBedRoom, "Lighting:");
    lv_obj_set_style_text_align(ui_LightBedRoom, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightBedRoom, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanBedRoom = lv_label_create(ui_BedRoom);
    lv_obj_set_width(ui_FanBedRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanBedRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanBedRoom, -1);
    lv_obj_set_y(ui_FanBedRoom, 32);
    lv_obj_set_align(ui_FanBedRoom, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_FanBedRoom, "Fan:");
    lv_obj_set_style_text_font(ui_FanBedRoom, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirBedRoom = lv_label_create(ui_BedRoom);
    lv_obj_set_width(ui_AirBedRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirBedRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AirBedRoom, -1);
    lv_obj_set_y(ui_AirBedRoom, 59);
    lv_obj_set_align(ui_AirBedRoom, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AirBedRoom, "AC:");
    lv_obj_set_style_text_font(ui_AirBedRoom, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titleComp1 = lv_label_create(ui_BedRoom);
    lv_obj_set_width(ui_titleComp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titleComp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titleComp1, 4);
    lv_obj_set_y(ui_titleComp1, -25);
    lv_obj_set_align(ui_titleComp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titleComp1, "Detail active device:");
    lv_obj_set_style_text_color(ui_titleComp1, lv_color_hex(0x00FF2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titleComp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_titleComp1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedActiveLight = lv_slider_create(ui_BedRoom);
    lv_slider_set_range(ui_BedActiveLight, 0, 3);
    lv_slider_set_value(ui_BedActiveLight, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BedActiveLight) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BedActiveLight, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_BedActiveLight, 89);
    lv_obj_set_height(ui_BedActiveLight, 11);
    lv_obj_set_x(ui_BedActiveLight, 35);
    lv_obj_set_y(ui_BedActiveLight, 3);
    lv_obj_set_align(ui_BedActiveLight, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BedActiveLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BedActiveLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedActiveFan = lv_slider_create(ui_BedRoom);
    lv_slider_set_range(ui_BedActiveFan, 0, 2);
    lv_slider_set_value(ui_BedActiveFan, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BedActiveFan) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BedActiveFan, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_BedActiveFan, 89);
    lv_obj_set_height(ui_BedActiveFan, 11);
    lv_obj_set_x(ui_BedActiveFan, 35);
    lv_obj_set_y(ui_BedActiveFan, 32);
    lv_obj_set_align(ui_BedActiveFan, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BedActiveFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BedActiveFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedActiveAC = lv_slider_create(ui_BedRoom);
    lv_slider_set_range(ui_BedActiveAC, 0, 2);
    lv_slider_set_value(ui_BedActiveAC, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BedActiveAC) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BedActiveAC, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BedActiveAC, 89);
    lv_obj_set_height(ui_BedActiveAC, 11);
    lv_obj_set_x(ui_BedActiveAC, 35);
    lv_obj_set_y(ui_BedActiveAC, 60);
    lv_obj_set_align(ui_BedActiveAC, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BedActiveAC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BedActiveAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CountLightB = lv_label_create(ui_BedRoom);
    lv_obj_set_width(ui_CountLightB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CountLightB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CountLightB, 110);
    lv_obj_set_y(ui_CountLightB, 2);
    lv_obj_set_align(ui_CountLightB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CountLightB, "(0)");
    lv_obj_set_style_text_font(ui_CountLightB, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CountFanB = lv_label_create(ui_BedRoom);
    lv_obj_set_width(ui_CountFanB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CountFanB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CountFanB, 110);
    lv_obj_set_y(ui_CountFanB, 30);
    lv_obj_set_align(ui_CountFanB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CountFanB, "(0)");
    lv_obj_set_style_text_font(ui_CountFanB, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CountACB = lv_label_create(ui_BedRoom);
    lv_obj_set_width(ui_CountACB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CountACB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CountACB, 110);
    lv_obj_set_y(ui_CountACB, 59);
    lv_obj_set_align(ui_CountACB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CountACB, "(0)");
    lv_obj_set_style_text_font(ui_CountACB, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LvRoom = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_LvRoom, 250);
    lv_obj_set_height(ui_LvRoom, 160);
    lv_obj_set_x(ui_LvRoom, -269);
    lv_obj_set_y(ui_LvRoom, 35);
    lv_obj_set_align(ui_LvRoom, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_LvRoom, lv_color_hex(0x002894), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LvRoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LvRoom, lv_color_hex(0x292525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LvRoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LvRoom, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LvRoom, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_LvRoom, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_LvRoom, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roomName1 = lv_label_create(ui_LvRoom);
    lv_obj_set_width(ui_roomName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_roomName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_roomName1, 2);
    lv_obj_set_y(ui_roomName1, 4);
    lv_obj_set_align(ui_roomName1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_roomName1, "LIVING ROOM");
    lv_obj_set_style_text_font(ui_roomName1, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLvRoom = lv_label_create(ui_LvRoom);
    lv_obj_set_width(ui_LightLvRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightLvRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightLvRoom, -1);
    lv_obj_set_y(ui_LightLvRoom, 5);
    lv_obj_set_align(ui_LightLvRoom, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LightLvRoom, "Lighting:");
    lv_obj_set_style_text_align(ui_LightLvRoom, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightLvRoom, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanLvRoom = lv_label_create(ui_LvRoom);
    lv_obj_set_width(ui_FanLvRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanLvRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanLvRoom, -1);
    lv_obj_set_y(ui_FanLvRoom, 32);
    lv_obj_set_align(ui_FanLvRoom, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_FanLvRoom, "Fan:");
    lv_obj_set_style_text_font(ui_FanLvRoom, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirLvRoom = lv_label_create(ui_LvRoom);
    lv_obj_set_width(ui_AirLvRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirLvRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AirLvRoom, -1);
    lv_obj_set_y(ui_AirLvRoom, 59);
    lv_obj_set_align(ui_AirLvRoom, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AirLvRoom, "AC:");
    lv_obj_set_style_text_font(ui_AirLvRoom, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titleComp = lv_label_create(ui_LvRoom);
    lv_obj_set_width(ui_titleComp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titleComp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titleComp, 4);
    lv_obj_set_y(ui_titleComp, -25);
    lv_obj_set_align(ui_titleComp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titleComp, "Detail active device:");
    lv_obj_set_style_text_color(ui_titleComp, lv_color_hex(0x00FF2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titleComp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_titleComp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivActiveLight = lv_slider_create(ui_LvRoom);
    lv_slider_set_range(ui_LivActiveLight, 0, 3);
    lv_slider_set_value(ui_LivActiveLight, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LivActiveLight) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LivActiveLight, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_LivActiveLight, 89);
    lv_obj_set_height(ui_LivActiveLight, 11);
    lv_obj_set_x(ui_LivActiveLight, 97);
    lv_obj_set_y(ui_LivActiveLight, 68);
    lv_obj_set_style_bg_color(ui_LivActiveLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LivActiveLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_LivActiveLight, 50, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CountLightLV = lv_label_create(ui_LvRoom);
    lv_obj_set_width(ui_CountLightLV, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CountLightLV, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CountLightLV, 109);
    lv_obj_set_y(ui_CountLightLV, 2);
    lv_obj_set_align(ui_CountLightLV, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CountLightLV, "(0)");
    lv_obj_set_style_text_font(ui_CountLightLV, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivActiveFan = lv_slider_create(ui_LvRoom);
    lv_slider_set_range(ui_LivActiveFan, 0, 2);
    lv_slider_set_value(ui_LivActiveFan, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LivActiveFan) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LivActiveFan, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_LivActiveFan, 89);
    lv_obj_set_height(ui_LivActiveFan, 11);
    lv_obj_set_x(ui_LivActiveFan, 35);
    lv_obj_set_y(ui_LivActiveFan, 33);
    lv_obj_set_align(ui_LivActiveFan, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LivActiveFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LivActiveFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CountFanLV = lv_label_create(ui_LvRoom);
    lv_obj_set_width(ui_CountFanLV, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CountFanLV, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CountFanLV, 109);
    lv_obj_set_y(ui_CountFanLV, 32);
    lv_obj_set_align(ui_CountFanLV, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CountFanLV, "(0)");
    lv_obj_set_style_text_font(ui_CountFanLV, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivActiveAC = lv_slider_create(ui_LvRoom);
    lv_slider_set_range(ui_LivActiveAC, 0, 2);
    lv_slider_set_value(ui_LivActiveAC, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LivActiveAC) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LivActiveAC, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LivActiveAC, 89);
    lv_obj_set_height(ui_LivActiveAC, 11);
    lv_obj_set_x(ui_LivActiveAC, 35);
    lv_obj_set_y(ui_LivActiveAC, 62);
    lv_obj_set_align(ui_LivActiveAC, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LivActiveAC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LivActiveAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CountACLV = lv_label_create(ui_LvRoom);
    lv_obj_set_width(ui_CountACLV, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CountACLV, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CountACLV, 109);
    lv_obj_set_y(ui_CountACLV, 62);
    lv_obj_set_align(ui_CountACLV, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CountACLV, "(0)");
    lv_obj_set_style_text_font(ui_CountACLV, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempChart = lv_arc_create(ui_mainScreen);
    lv_obj_set_width(ui_TempChart, 200);
    lv_obj_set_height(ui_TempChart, 200);
    lv_obj_set_x(ui_TempChart, -274);
    lv_obj_set_y(ui_TempChart, -80);
    lv_obj_set_align(ui_TempChart, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_TempChart, 40);
    lv_obj_set_style_arc_color(ui_TempChart, lv_color_hex(0xD3D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_TempChart, lv_color_hex(0xAD0909), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempChart, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TempChart, lv_color_hex(0xAD0909), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempChart, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TitleTemp = lv_label_create(ui_TempChart);
    lv_obj_set_width(ui_TitleTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleTemp, 8);
    lv_obj_set_y(ui_TitleTemp, -14);
    lv_obj_set_align(ui_TitleTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleTemp, "Temperature:");
    lv_obj_set_style_text_color(ui_TitleTemp, lv_color_hex(0xAD0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleTemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueTemp = lv_label_create(ui_TempChart);
    lv_obj_set_width(ui_ValueTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueTemp, 7);
    lv_obj_set_y(ui_ValueTemp, 20);
    lv_obj_set_align(ui_ValueTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueTemp, "20°C");
    lv_obj_set_style_text_color(ui_ValueTemp, lv_color_hex(0xAD0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueTemp, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityChart = lv_arc_create(ui_mainScreen);
    lv_obj_set_width(ui_HumidityChart, 200);
    lv_obj_set_height(ui_HumidityChart, 200);
    lv_obj_set_x(ui_HumidityChart, -275);
    lv_obj_set_y(ui_HumidityChart, 116);
    lv_obj_set_align(ui_HumidityChart, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_HumidityChart, 50);
    lv_obj_set_style_arc_color(ui_HumidityChart, lv_color_hex(0xB6B6C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_HumidityChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_HumidityChart, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_HumidityChart, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_TitleHumi = lv_label_create(ui_HumidityChart);
    lv_obj_set_width(ui_TitleHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleHumi, 3);
    lv_obj_set_y(ui_TitleHumi, -19);
    lv_obj_set_align(ui_TitleHumi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleHumi, "Humidity:");
    lv_obj_set_style_text_color(ui_TitleHumi, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleHumi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleHumi, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueHumi = lv_label_create(ui_HumidityChart);
    lv_obj_set_width(ui_ValueHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueHumi, 6);
    lv_obj_set_y(ui_ValueHumi, 17);
    lv_obj_set_align(ui_ValueHumi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueHumi, "50%");
    lv_obj_set_style_text_color(ui_ValueHumi, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueHumi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueHumi, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaedMain = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_HeaedMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeaedMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeaedMain, 131);
    lv_obj_set_y(ui_HeaedMain, -222);
    lv_obj_set_align(ui_HeaedMain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeaedMain, "MANAGER ROOM");
    lv_obj_set_style_text_color(ui_HeaedMain, lv_color_hex(0x1A0ED8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeaedMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HeaedMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HeaedMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaedMain, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleVIEW = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_TitleVIEW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleVIEW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleVIEW, -277);
    lv_obj_set_y(ui_TitleVIEW, -219);
    lv_obj_set_align(ui_TitleVIEW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleVIEW, "VIEW");
    lv_obj_set_style_text_color(ui_TitleVIEW, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleVIEW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleVIEW, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BedRoom, ui_event_BedRoom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LvRoom, ui_event_LvRoom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempChart, ui_event_TempChart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HumidityChart, ui_event_HumidityChart, LV_EVENT_ALL, NULL);

}

void ui_mainScreen_screen_destroy(void)
{
    if(ui_mainScreen) lv_obj_del(ui_mainScreen);

    // NULL screen variables
    ui_mainScreen = NULL;
    ui_TabView1 = NULL;
    ui_TabView2 = NULL;
    ui_BedRoom = NULL;
    ui_roomName4 = NULL;
    ui_LightBedRoom = NULL;
    ui_FanBedRoom = NULL;
    ui_AirBedRoom = NULL;
    ui_titleComp1 = NULL;
    ui_BedActiveLight = NULL;
    ui_BedActiveFan = NULL;
    ui_BedActiveAC = NULL;
    ui_CountLightB = NULL;
    ui_CountFanB = NULL;
    ui_CountACB = NULL;
    ui_LvRoom = NULL;
    ui_roomName1 = NULL;
    ui_LightLvRoom = NULL;
    ui_FanLvRoom = NULL;
    ui_AirLvRoom = NULL;
    ui_titleComp = NULL;
    ui_LivActiveLight = NULL;
    ui_CountLightLV = NULL;
    ui_LivActiveFan = NULL;
    ui_CountFanLV = NULL;
    ui_LivActiveAC = NULL;
    ui_CountACLV = NULL;
    ui_TempChart = NULL;
    ui_TitleTemp = NULL;
    ui_ValueTemp = NULL;
    ui_HumidityChart = NULL;
    ui_TitleHumi = NULL;
    ui_ValueHumi = NULL;
    ui_HeaedMain = NULL;
    ui_TitleVIEW = NULL;

}
