// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Squareline

#include "../ui.h"

void ui_SetingWifi_screen_init(void)
{
    ui_SetingWifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SetingWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetingWifi, lv_color_hex(0x70C5CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetingWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header = lv_label_create(ui_SetingWifi);
    lv_obj_set_width(ui_Header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Header, 0);
    lv_obj_set_y(ui_Header, -165);
    lv_obj_set_align(ui_Header, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Header, "BK SMART HOME\n   WIFI SETING");
    lv_obj_set_style_text_font(ui_Header, &ui_font_Font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImportName = lv_textarea_create(ui_SetingWifi);
    lv_obj_set_width(ui_ImportName, 390);
    lv_obj_set_height(ui_ImportName, 53);
    lv_obj_set_x(ui_ImportName, -9);
    lv_obj_set_y(ui_ImportName, -71);
    lv_obj_set_align(ui_ImportName, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ImportName, "Nhap ten WIFI");
    lv_obj_set_style_text_color(ui_ImportName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ImportName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImportName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImportName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImportName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ImportName, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(ui_ImportName, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ImportName, 255, LV_PART_CURSOR | LV_STATE_FOCUSED);

    ui_ImportPass = lv_textarea_create(ui_SetingWifi);
    lv_obj_set_width(ui_ImportPass, 390);
    lv_obj_set_height(ui_ImportPass, 53);
    lv_obj_set_x(ui_ImportPass, -9);
    lv_obj_set_y(ui_ImportPass, 0);
    lv_obj_set_align(ui_ImportPass, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ImportPass, "Nhap password");
    lv_obj_set_style_text_color(ui_ImportPass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ImportPass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImportPass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImportPass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ImportPass, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ImportPass, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImportPass, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ImportPass, 255, LV_PART_CURSOR | LV_STATE_FOCUSED);

    ui_ConnectWF = lv_btn_create(ui_SetingWifi);
    lv_obj_set_width(ui_ConnectWF, 135);
    lv_obj_set_height(ui_ConnectWF, 50);
    lv_obj_set_x(ui_ConnectWF, 287);
    lv_obj_set_y(ui_ConnectWF, -31);
    lv_obj_set_align(ui_ConnectWF, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ConnectWF, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConnectWF, lv_color_hex(0x352DB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectWF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ConnectWF);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 3);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Complete");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_SetingWifi);
    lv_obj_set_width(ui_Keyboard1, 628);
    lv_obj_set_height(ui_Keyboard1, 192);
    lv_obj_set_x(ui_Keyboard1, 3);
    lv_obj_set_y(ui_Keyboard1, 111);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_ImportName, ui_event_ImportName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImportPass, ui_event_ImportPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConnectWF, ui_event_ConnectWF, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_ImportName);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

}
