// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Squareline

#ifndef UI_SETINGWIFI_H
#define UI_SETINGWIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SetingWifi
extern void ui_SetingWifi_screen_init(void);
extern void ui_SetingWifi_screen_destroy(void);
extern lv_obj_t * ui_SetingWifi;
extern lv_obj_t * ui_Header;
extern void ui_event_ImportName(lv_event_t * e);
extern lv_obj_t * ui_ImportName;
extern void ui_event_ImportPass(lv_event_t * e);
extern lv_obj_t * ui_ImportPass;
extern void ui_event_ConnectWF(lv_event_t * e);
extern lv_obj_t * ui_ConnectWF;
extern lv_obj_t * ui_Label2;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

