// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Squareline

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_SetingWifi
void ui_SetingWifi_screen_init(void);
lv_obj_t * ui_SetingWifi;
lv_obj_t * ui_Header;
void ui_event_ImportName(lv_event_t * e);
lv_obj_t * ui_ImportName;
void ui_event_ImportPass(lv_event_t * e);
lv_obj_t * ui_ImportPass;
void ui_event_ConnectWF(lv_event_t * e);
lv_obj_t * ui_ConnectWF;
lv_obj_t * ui_Label2;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabView2;
void ui_event_BedRoom(lv_event_t * e);
lv_obj_t * ui_BedRoom;
lv_obj_t * ui_roomName4;
lv_obj_t * ui_LightBedRoom;
lv_obj_t * ui_FanBedRoom;
lv_obj_t * ui_AirBedRoom;
lv_obj_t * ui_titleComp1;
lv_obj_t * ui_BedActiveLight;
lv_obj_t * ui_BedActiveFan;
lv_obj_t * ui_BedActiveAC;
lv_obj_t * ui_CountLightB;
lv_obj_t * ui_CountFanB;
lv_obj_t * ui_CountACB;
void ui_event_LvRoom(lv_event_t * e);
lv_obj_t * ui_LvRoom;
lv_obj_t * ui_roomName1;
lv_obj_t * ui_LightLvRoom;
lv_obj_t * ui_FanLvRoom;
lv_obj_t * ui_AirLvRoom;
lv_obj_t * ui_titleComp;
lv_obj_t * ui_LivActiveLight;
lv_obj_t * ui_CountLightLV;
lv_obj_t * ui_LivActiveFan;
lv_obj_t * ui_CountFanLV;
lv_obj_t * ui_LivActiveAC;
lv_obj_t * ui_CountACLV;
void ui_event_TempChart(lv_event_t * e);
lv_obj_t * ui_TempChart;
lv_obj_t * ui_TitleTemp;
lv_obj_t * ui_ValueTemp;
void ui_event_HumidityChart(lv_event_t * e);
lv_obj_t * ui_HumidityChart;
lv_obj_t * ui_TitleHumi;
lv_obj_t * ui_ValueHumi;
lv_obj_t * ui_HeaedMain;
lv_obj_t * ui_TitleVIEW;
// CUSTOM VARIABLES

// SCREEN: ui_LVRoomScreen
void ui_LVRoomScreen_screen_init(void);
lv_obj_t * ui_LVRoomScreen;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_dvName1;
void ui_event_LightLvRoom1(lv_event_t * e);
lv_obj_t * ui_LightLvRoom1;
void ui_event_LightLvRoom2(lv_event_t * e);
lv_obj_t * ui_LightLvRoom2;
void ui_event_LightLvRoom3(lv_event_t * e);
lv_obj_t * ui_LightLvRoom3;
void ui_event_BackHome(lv_event_t * e);
lv_obj_t * ui_BackHome;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_dvName2;
void ui_event_FanLvRoom1(lv_event_t * e);
lv_obj_t * ui_FanLvRoom1;
void ui_event_FanLvRoom2(lv_event_t * e);
lv_obj_t * ui_FanLvRoom2;
lv_obj_t * ui_Fan1;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_ACName1;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
lv_obj_t * ui_LIGHT_Bulb_1_;
lv_obj_t * ui_LIGHT_Bulb_2;
lv_obj_t * ui_LIGHT_Bulb_3;
lv_obj_t * ui_Fan2;
// CUSTOM VARIABLES

// SCREEN: ui_BedoomSceen
void ui_BedoomSceen_screen_init(void);
lv_obj_t * ui_BedoomSceen;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_dvName3;
lv_obj_t * ui_LightBedRoom1;
lv_obj_t * ui_LightBedRoom2;
lv_obj_t * ui_LightBedRoom3;
void ui_event_BackHome2(lv_event_t * e);
lv_obj_t * ui_BackHome2;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_dvName4;
lv_obj_t * ui_FanBedRoom1;
lv_obj_t * ui_FanBedRoom2;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_ACName3;
lv_obj_t * ui_ACBedRoom1;
lv_obj_t * ui_Lightbed1;
lv_obj_t * ui_Lightbed2;
lv_obj_t * ui_Lightbed3;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ImportName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_ImportName);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ImportPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_ImportPass);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ConnectWF(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connectToWiFi(e);
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_BedRoom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BedoomSceen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_BedoomSceen_screen_init);
    }
}

void ui_event_LvRoom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LVRoomScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_LVRoomScreen_screen_init);
    }
}

void ui_event_TempChart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_ValueTemp, target, "", "°C");
    }
}

void ui_event_HumidityChart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_ValueHumi, target, "", "%");
    }
}

void ui_event_LightLvRoom1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LvR_light1(e);
    }
}

void ui_event_LightLvRoom2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LvR_light2(e);
    }
}

void ui_event_LightLvRoom3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LvR_light3(e);
    }
}

void ui_event_BackHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_mainScreen_screen_init);
    }
}

void ui_event_FanLvRoom1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LvR_fan1(e);
    }
}

void ui_event_FanLvRoom2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LvR_fan2(e);
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LvR_air1(e);
    }
}

void ui_event_BackHome2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_mainScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SetingWifi_screen_init();
    ui_mainScreen_screen_init();
    ui_LVRoomScreen_screen_init();
    ui_BedoomSceen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SetingWifi);
}
