// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: Squareline

#ifndef _SQUARELINE_UI_H
#define _SQUARELINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Initial_Screen.h"
#include "screens/ui_SetingWifi.h"
#include "screens/ui_mainScreen.h"
#include "screens/ui_LVRoomScreen.h"
#include "screens/ui_BedoomSceen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_hcmut_png);    // assets/hcmut.png
LV_IMG_DECLARE(ui_img_1385603933);    // assets/icons8-left-25.png

// FONTS
LV_FONT_DECLARE(ui_font_Font20);
LV_FONT_DECLARE(ui_font_Font30);
LV_FONT_DECLARE(ui_font_Font48);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
